apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: fsight
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gabinn/fsight-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: QDRANT_HOST
              value: qdrant
            - name: QDRANT_PORT
              value: "6333"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fsight-secrets
                  key: OPENAI_API_KEY
            - name: VOYAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fsight-secrets
                  key: VOYAGE_API_KEY
          readinessProbe:
            httpGet:
              path: /dates
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
