apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fsight-api
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: app
  namespaceSelector:
    matchNames:
      - fsight
  selector:
    matchLabels:
      app: fsight-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
