FROM python:3.11-slim
WORKDIR /app
COPY requirements.ingestor.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY scripts/config.py .
COPY scripts/ingestor.py .
CMD ["sleep", "infinity"]
