FROM python:3.11-slim
WORKDIR /app
COPY requirements.api.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY scripts/config.py .
COPY scripts/api.py .
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
